@include('header')
@yield('home')
@yield('table')
@yield('category_table')
@yield('add_category')
@yield('update_category')
@yield('add_app')
@yield('app_table')
@yield('update_app')
@yield('show_ad')
@yield('update_ad')
@yield('change_password')
@yield('add_ringtone_form')
@yield('ringtone_table')
@yield('add_wallpaper_form')
@yield('wallpaper_table')
@yield('update_wallpaper_form')


@include('footer')